services:
  - name: web
    env: python
    build_command: pip install -r requirements.txt
    start_command: gunicorn your_project_name.wsgi:application
    env_vars:
      - key: DJANGO_SETTINGS_MODULE
        value: "your_project_name.settings"
