# Generated by Django 5.0.2 on 2024-02-14 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(max_length=50)),
                ('base_distance_in_km', models.PositiveIntegerField(default=5)),
                ('perishable_km_price', models.PositiveIntegerField(default=150)),
                ('non_perishable_km_price', models.PositiveIntegerField(default=100)),
                ('fix_price', models.PositiveIntegerField(default=1000)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery_api.item')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery_api.organization')),
            ],
        ),
    ]
